### ISSUE TITLE
run issues

### ISSUE THREAD

**Issue by aminebenjemaa** [leyleo/TeamDisk_iOS#1]
hi,
plz when i try to run temdisk_ios an error message is displayed
"Use undeclared identifier 'LEOExtendUTIConvert" in LEODEtailsViewController.m & LEODoublModeViewController

thanks for Reply

**Comment by leyleo** [comment]
plz check the file "LEOContentTypeConvert.h"

**Comment by aminebenjemaa** [comment]
#import <Foundation/Foundation.h>
#import "LEODefines.h"

@interface LEOContentTypeConvert : NSObject
{
    NSMutableDictionary *_folderDic;
    NSMutableDictionary *_fileDic;
}
+(LEOContentTypeConvert *)getInstance;
-(NSString *)searchForResourceType:(NSString *)type isFile:(BOOL)isFile;
@end

@interface LEOExtendUTIConvert : NSObject
{
    NSMutableDictionary *_covertDic;
}
+(LEOExtendUTIConvert *)getInstance;
-(NSString *)searchForUTI:(NSString *)type;
@end

@interface LEOExtensionToMIME : NSObject
{
    NSMutableDictionary *_convertDic;
}
+(LEOExtensionToMIME *)getInstance;
-(NSString *)searchMimeFromExtension:(NSString *)extension;
@end

**Comment by RainyLave** [comment]
well, when you add leowebdav documents into the xcode project, you could move LeoContentTypeCovert.h and  LeoContentTypeCovert.m beforehand, or there would  be an unexpected conflict  between  the files in utility and leowebdav documents.
