### ISSUE TITLE
Use of undeclared identifier

### ISSUE THREAD

**Issue by aminebenjemaa** [leyleo/TeamDisk_iOS#2]
hi,
plz i have error in LEODoubleModeViewController.m
Use of undeclared identifier "LEOContentTypeConvert"

**Comment by leyleo** [comment]
import the "LEOContentTypeConvert.h" to your "LEODoubleModeViewController.m"

**Comment by aminebenjemaa** [comment]
this is already done

**Comment by leyleo** [comment]
how could i help u? I couldn't image what's the matter. Maybe you check out the project again? or send your codes to me via email

**Comment by aminebenjemaa** [comment]
ok i will send code for you

**Comment by leyleo** [comment]
maybe the really problem is the project can't find classes from leowebdav. try the following method to checkout the whole project:

```
git clone https://github.com/leyleo/TeamDisk_iOS.git
cd TeamDisk_iOS
git submodule init
git submodule update
```

**Comment by aminebenjemaa** [comment]
thank's for help it work
