### ISSUE TITLE
TeamDisk_iOS configuration

### ISSUE THREAD

**Issue by aminebenjemaa** [leyleo/TeamDisk_iOS#3]
hi,
sorry i have other question,
 i have sevrer webdav i can connect with TeamDisk_ios but
i can't navigate  in my fonder &
i can't read file(ils,word,pdf,etc)with error fail to find file
there is a config to do ?

**Comment by aminebenjemaa** [comment]
owncloud owncloud server webdav

**Comment by leyleo** [comment]
plz check out leowebdav for latest update. issue is fixed.

**Comment by aminebenjemaa** [comment]
thanks it work
