### ISSUE TITLE
opening files from webdav server

### ISSUE THREAD

**Issue by mahermeg17** [leyleo/TeamDisk_iOS#4]
Hi,

Great app. it works when connecting to the sample server http://w.4meapp.com/webdav
But not when tested with owncloud :

http://demo.owncloud.org/remote.php/webdav
user : test
pw :test

The LEOWebDAV project works fine with the same webdav server (http://demo.owncloud.org/remote.php/webdav).

can you help me to fix this issue.

best regards.

**Comment by leyleo** [comment]
yep, there is a mistake about the file path, i'll fix it recently.

**Comment by leyleo** [comment]
update the leowebdav
